/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Alertas.Sesion;
import Paneles.AgregarEspecialista;
import Paneles.CambiaPanel;
import Paneles.Configuracion;
import Paneles.ConsultaEspecialista;
import Paneles.EliminarEspecialista;
import Paneles.ModificarEspecialista;
import Paneles.Principal;
import java.awt.Color;

/**
 *
 * @author Gibran Ramses
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        new CambiaPanel(PanelPrincipal, new Principal());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Superior = new javax.swing.JPanel();
        minBtn = new javax.swing.JPanel();
        minTxt = new javax.swing.JLabel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        rSButtonMetro2 = new rsbuttom.RSButtonMetro();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JLabel();
        BotonIn = new rsbuttom.RSButtonMetro();
        BotonEs = new rsbuttom.RSButtonMetro();
        BotonCo = new rsbuttom.RSButtonMetro();
        BotonPa = new rsbuttom.RSButtonMetro();
        BotonCi = new rsbuttom.RSButtonMetro();
        BotonSa = new rsbuttom.RSButtonMetro();
        BotonEm1 = new rsbuttom.RSButtonMetro();
        PanelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        Superior.setBackground(new java.awt.Color(67, 141, 184));
        Superior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minBtn.setBackground(new java.awt.Color(67, 141, 184));

        minTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        minTxt.setForeground(new java.awt.Color(255, 255, 255));
        minTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minTxt.setText("---");
        minTxt.setToolTipText("");
        minTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        minTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        minTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout minBtnLayout = new javax.swing.GroupLayout(minBtn);
        minBtn.setLayout(minBtnLayout);
        minBtnLayout.setHorizontalGroup(
            minBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, minBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(minTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        minBtnLayout.setVerticalGroup(
            minBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, minBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(minTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Superior.add(minBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 10, -1, -1));

        exitBtn.setBackground(new java.awt.Color(67, 141, 184));

        exitTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exitTxt.setForeground(new java.awt.Color(255, 255, 255));
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(exitBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(exitBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Superior.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 10, -1, -1));

        rSButtonMetro2.setBackground(new java.awt.Color(67, 141, 184));
        rSButtonMetro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MENU/menu.png"))); // NOI18N
        rSButtonMetro2.setColorHover(new java.awt.Color(67, 141, 184));
        rSButtonMetro2.setColorNormal(new java.awt.Color(67, 141, 184));
        rSButtonMetro2.setColorPressed(new java.awt.Color(67, 141, 184));
        Superior.add(rSButtonMetro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Doctolandia");
        Superior.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 200, 30));

        jPanel2.setBackground(new java.awt.Color(67, 141, 184));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(67, 141, 184));

        txtUsuario.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MENU/USER.png"))); // NOI18N
        txtUsuario.setText("Administrador");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, -1));

        BotonIn.setBackground(new java.awt.Color(67, 141, 184));
        BotonIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MENU/INICIO.png"))); // NOI18N
        BotonIn.setText("Inicio");
        BotonIn.setColorNormal(new java.awt.Color(67, 141, 184));
        BotonIn.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BotonIn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonIn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BotonIn.setIconTextGap(25);
        BotonIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInActionPerformed(evt);
            }
        });
        jPanel2.add(BotonIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 89, 240, 43));

        BotonEs.setBackground(new java.awt.Color(67, 141, 184));
        BotonEs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MENU/ESPECIALISTA.png"))); // NOI18N
        BotonEs.setText("Especialista");
        BotonEs.setColorNormal(new java.awt.Color(67, 141, 184));
        BotonEs.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BotonEs.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonEs.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BotonEs.setIconTextGap(25);
        BotonEs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEsActionPerformed(evt);
            }
        });
        jPanel2.add(BotonEs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 240, 43));

        BotonCo.setBackground(new java.awt.Color(67, 141, 184));
        BotonCo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MENU/EMPLEADO.png"))); // NOI18N
        BotonCo.setText("Empleado");
        BotonCo.setColorNormal(new java.awt.Color(67, 141, 184));
        BotonCo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BotonCo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonCo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BotonCo.setIconTextGap(25);
        BotonCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCoActionPerformed(evt);
            }
        });
        jPanel2.add(BotonCo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 239, 46));

        BotonPa.setBackground(new java.awt.Color(67, 141, 184));
        BotonPa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MENU/PACIENTE.png"))); // NOI18N
        BotonPa.setText("Paciente");
        BotonPa.setToolTipText("");
        BotonPa.setColorNormal(new java.awt.Color(67, 141, 184));
        BotonPa.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BotonPa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonPa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BotonPa.setIconTextGap(25);
        BotonPa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPaActionPerformed(evt);
            }
        });
        jPanel2.add(BotonPa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 239, 44));

        BotonCi.setBackground(new java.awt.Color(67, 141, 184));
        BotonCi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MENU/CITA.png"))); // NOI18N
        BotonCi.setText("Cita");
        BotonCi.setToolTipText("");
        BotonCi.setColorNormal(new java.awt.Color(67, 141, 184));
        BotonCi.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BotonCi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonCi.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BotonCi.setIconTextGap(25);
        BotonCi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCiActionPerformed(evt);
            }
        });
        jPanel2.add(BotonCi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 239, 44));

        BotonSa.setBackground(new java.awt.Color(67, 141, 184));
        BotonSa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MENU/EXIT.png"))); // NOI18N
        BotonSa.setText("Salir");
        BotonSa.setColorHover(new java.awt.Color(153, 0, 0));
        BotonSa.setColorNormal(new java.awt.Color(67, 141, 184));
        BotonSa.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BotonSa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSaActionPerformed(evt);
            }
        });
        jPanel2.add(BotonSa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 239, 43));

        BotonEm1.setBackground(new java.awt.Color(67, 141, 184));
        BotonEm1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MENU/CONFIGURACION.png"))); // NOI18N
        BotonEm1.setText("Configuración");
        BotonEm1.setColorNormal(new java.awt.Color(67, 141, 184));
        BotonEm1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BotonEm1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotonEm1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BotonEm1.setIconTextGap(25);
        BotonEm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEm1ActionPerformed(evt);
            }
        });
        jPanel2.add(BotonEm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 239, 46));

        PanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        PanelPrincipal.setLayout(new javax.swing.BoxLayout(PanelPrincipal, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Superior, javax.swing.GroupLayout.DEFAULT_SIZE, 1538, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Superior, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        Sesion a = new Sesion(null, true);
        a.ms.setText("Menu");
        a.setVisible(true);
        if (a.r.getText().equals("si")) {
            Login newframe= new Login();
            newframe.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(new Color(67,141,184));
        exitTxt.setForeground(Color.WHITE);
    }//GEN-LAST:event_exitTxtMouseExited

    private void minTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minTxtMouseClicked
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_minTxtMouseClicked

    private void minTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minTxtMouseEntered
        minBtn.setBackground(Color.gray);
        minTxt.setForeground(Color.white);
    }//GEN-LAST:event_minTxtMouseEntered

    private void minTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minTxtMouseExited
        minBtn.setBackground(new Color(67,141,184));
        minTxt.setForeground(Color.WHITE);
    }//GEN-LAST:event_minTxtMouseExited

    private void BotonInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(PanelPrincipal, new Principal());
    }//GEN-LAST:event_BotonInActionPerformed

    private void BotonEsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEsActionPerformed
        // TODO add your handling code here:
        if (txtUsuario.getText().equals("Administrador")) {
            Especialista newframe= new Especialista();
            newframe.setVisible(true);
            newframe.txtUsuarioEs.setText(txtUsuario.getText());
            this.dispose();
        }else{
            Alertas.Error a = new Alertas.Error(null, true);
            a.title.setText("Sin Acceso");
            a.ms.setText("No dispone de los permisos necesarios");
            a.setVisible(true);
        }
    }//GEN-LAST:event_BotonEsActionPerformed

    private void BotonCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCoActionPerformed
        // TODO add your handling code here:
        if (txtUsuario.getText().equals("Administrador")) {
            Empleado newframe= new Empleado();
            newframe.setVisible(true);
            newframe.txtUsuarioEm.setText(txtUsuario.getText());
            this.dispose();
        }else{
            Alertas.Error a = new Alertas.Error(null, true);
            a.title.setText("Sin Acceso");
            a.ms.setText("No dispone de los permisos necesarios");
            a.setVisible(true);
        }
    }//GEN-LAST:event_BotonCoActionPerformed

    private void BotonPaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPaActionPerformed
        // TODO add your handling code here:
         Paciente newframe= new Paciente();
         newframe.setVisible(true);
         newframe.txtUsuarioPa.setText(txtUsuario.getText());
         this.dispose();
    }//GEN-LAST:event_BotonPaActionPerformed

    private void BotonCiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCiActionPerformed
        // TODO add your handling code here:
         Cita newframe= new Cita();
         newframe.setVisible(true);
         newframe.txtUsuarioC.setText(txtUsuario.getText());
         this.dispose();
    }//GEN-LAST:event_BotonCiActionPerformed

    private void BotonSaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSaActionPerformed
        // TODO add your handling code here:
        Sesion a = new Sesion(null, true);
        a.ms.setText("Menu");
        a.setVisible(true);
        if (a.r.getText().equals("si")) {
            Login newframe= new Login();
            newframe.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_BotonSaActionPerformed

    private void BotonEm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEm1ActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(PanelPrincipal, new Configuracion());
    }//GEN-LAST:event_BotonEm1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro BotonCi;
    private rsbuttom.RSButtonMetro BotonCo;
    private rsbuttom.RSButtonMetro BotonEm1;
    private rsbuttom.RSButtonMetro BotonEs;
    private rsbuttom.RSButtonMetro BotonIn;
    private rsbuttom.RSButtonMetro BotonPa;
    private rsbuttom.RSButtonMetro BotonSa;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel Superior;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel minBtn;
    private javax.swing.JLabel minTxt;
    private rsbuttom.RSButtonMetro rSButtonMetro2;
    public javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables
}
