/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import java.awt.Color;
import java.awt.Image;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import mysql.Conexion_BD;
import mysql.Metodos_mysql;

/**
 *
 * @author Gibran Ramses
 */
public final class AgregarCita extends javax.swing.JPanel {

    private static Connection conexion;
    private static PreparedStatement sentencia_preparada;
    private static ResultSet resultado;
    
    Metodos_mysql metodos=new Metodos_mysql();
    int idCita;
    String fecha;
    String hora;
    String motivo;
    String idPaciente;
    String idEspecialista;
    String precio;

    /**
     * Creates new form ConsultaEspecialista
     */
    public AgregarCita() {
        initComponents();
        imagen_png_guardar();
        bloquear();
    }

    public void imagen_gif_guardar() {
        ImageIcon check_gif;
        check_gif = new ImageIcon(getClass().getResource("/Imagenes/VENTANAS/CHECK.gif"));
        Icon gif = new ImageIcon(check_gif.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT));
        botonGuardar.setIcon(gif);
    }
    
    public void imagen_png_guardar() {
        ImageIcon check_png;
        check_png = new ImageIcon(getClass().getResource("/Imagenes/VENTANAS/CHECK.png"));
        Icon png = new ImageIcon(check_png.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT));
        botonGuardar.setIcon(png);
    }
    
    public void validacion(){
        String campo= txtid.getText();
        boolean isNumeric =  campo.matches("[+-]?\\d*(\\\\d+)?"); 
        
        if(isNumeric==false){
            txtvalidar.setText("El ID solo puede contener numeros enteros");
            txtvalidar.setForeground(new Color(102,0,0));
            limpiar();
            bloquear();
        }
        
        if(campo != "" && isNumeric == true){
            String mensaje=metodos.buscar_idCita(txtid.getText());
        
            if(mensaje.equals("Existe ID")){
                txtvalidar.setText("El ID ya se encuentra registrado");
                txtvalidar.setForeground(new Color(102,0,0));
                limpiar();
                bloquear();  
            }
        
            if(mensaje.equals("No Existe ID")){
            txtvalidar.setText("El ID no esta registrado");
            txtvalidar.setForeground(Color.BLACK);
            desbloquear();
            }
        }
        
        if("".equals(campo)){
            txtvalidar.setText("");
            limpiar();
            bloquear();
        }
    }
    
    
        public void bloquear(){
        txtFecha.setEnabled(false);
        txtHora.setEnabled(false);
        txtMotivo.setEnabled(false);
        txtidPaciente.setEnabled(false);
        txtidEspecialista.setEnabled(false);
        txtPrecio.setEnabled(false);
        botonGuardar.setEnabled(false);
        jButton1.setEnabled(false);
    }
    
    public void desbloquear(){
        txtFecha.setEnabled(true);
        txtHora.setEnabled(true);
        txtMotivo.setEnabled(true);
        txtidPaciente.setEnabled(true);
        txtidEspecialista.setEnabled(true);
        txtPrecio.setEnabled(true);
        botonGuardar.setEnabled(true);
        jButton1.setEnabled(true);
    }
    
    
    public void limpiar(){
        txtHora.setText("Ingrese la Hora");
        txtHora.setForeground(new Color(153,153,153));
        txtMotivo.setText("Ingrese el Motivo");
        txtMotivo.setForeground(new Color(153,153,153));
        txtidPaciente.setText("Ingrese el idPaciente");
        txtidPaciente.setForeground(new Color(153,153,153));
        txtidEspecialista.setText("Ingrese el idEspecialista");
        txtidEspecialista.setForeground(new Color(153,153,153));
        txtPrecio.setText("Ingrese el Precio");
        txtPrecio.setForeground(new Color(153,153,153));
        validaridP.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTimeChooserDemo1 = new lu.tudor.santec.jtimechooser.demo.JTimeChooserDemo();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMotivo = new javax.swing.JTextField();
        txtidPaciente = new javax.swing.JTextField();
        txtidEspecialista = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtvalidar = new javax.swing.JLabel();
        valiidarnombre = new javax.swing.JLabel();
        validarapePa = new javax.swing.JLabel();
        validarapeMa = new javax.swing.JLabel();
        validaridP = new javax.swing.JLabel();
        validaridE = new javax.swing.JLabel();
        validarCa = new javax.swing.JLabel();
        txtFecha = new com.toedter.calendar.JDateChooser();
        txtHora = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        botonGuardar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(169, 195, 212));
        setPreferredSize(new java.awt.Dimension(1284, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        jLabel3.setText("Agregar");
        jLabel3.setToolTipText("");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 23, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel4.setText("Ingrese los datos de la Cita");
        jLabel4.setToolTipText("");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 78, -1, -1));

        jPanel1.setBackground(new java.awt.Color(177, 182, 198));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setText("ID : ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 24, -1, 46));

        txtid.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtid.setForeground(new java.awt.Color(153, 153, 153));
        txtid.setText("Ingrese el ID");
        txtid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtidMousePressed(evt);
            }
        });
        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidKeyReleased(evt);
            }
        });
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 27, 294, 46));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel2.setText(" Fecha: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 137, -1, 46));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel6.setText("Hora : ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 198, 46));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel7.setText("Motivo : ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 46));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel9.setText("idPaciente : ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, 46));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel10.setText("idEspecialista : ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, 46));

        txtMotivo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtMotivo.setForeground(new java.awt.Color(153, 153, 153));
        txtMotivo.setText("Ingrese el Motivo");
        txtMotivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtMotivoMousePressed(evt);
            }
        });
        jPanel1.add(txtMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 294, 46));

        txtidPaciente.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtidPaciente.setForeground(new java.awt.Color(153, 153, 153));
        txtidPaciente.setText("Ingrese el idPaciente");
        txtidPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtidPacienteMousePressed(evt);
            }
        });
        txtidPaciente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidPacienteKeyReleased(evt);
            }
        });
        jPanel1.add(txtidPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 294, 46));

        txtidEspecialista.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtidEspecialista.setForeground(new java.awt.Color(153, 153, 153));
        txtidEspecialista.setText("Ingrese el idEspecialista");
        txtidEspecialista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtidEspecialistaMousePressed(evt);
            }
        });
        jPanel1.add(txtidEspecialista, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 294, 46));

        txtPrecio.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(153, 153, 153));
        txtPrecio.setText("Ingrese el Precio");
        txtPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPrecioMousePressed(evt);
            }
        });
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 294, 46));

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel12.setText("Precio : ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, -1, 46));

        txtvalidar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jPanel1.add(txtvalidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 91, 440, 33));

        valiidarnombre.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        valiidarnombre.setForeground(new java.awt.Color(102, 0, 0));
        jPanel1.add(valiidarnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 290, 30));

        validarapePa.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        validarapePa.setForeground(new java.awt.Color(102, 0, 0));
        jPanel1.add(validarapePa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 290, 30));

        validarapeMa.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        validarapeMa.setForeground(new java.awt.Color(102, 0, 0));
        jPanel1.add(validarapeMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 290, 30));

        validaridP.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        validaridP.setForeground(new java.awt.Color(102, 0, 0));
        jPanel1.add(validaridP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 290, 30));

        validaridE.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        validaridE.setForeground(new java.awt.Color(102, 0, 0));
        jPanel1.add(validaridE, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 290, 30));

        validarCa.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        validarCa.setForeground(new java.awt.Color(102, 0, 0));
        jPanel1.add(validarCa, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, 290, 30));

        txtFecha.setToolTipText("");
        txtFecha.setDateFormatString("yyyy-MM-dd");
        txtFecha.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 290, 50));

        txtHora.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtHora.setForeground(new java.awt.Color(153, 153, 153));
        txtHora.setText("Ingrese la Hora");
        txtHora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtHoraMousePressed(evt);
            }
        });
        jPanel1.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 294, 46));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 114, 1036, 600));

        jPanel2.setBackground(new java.awt.Color(177, 182, 198));

        botonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonGuardarMouseExited(evt);
            }
        });
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VENTANAS/BORRAR.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel17.setText("Agregar");
        jLabel17.setToolTipText("");

        jLabel18.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel18.setText("Borrar");
        jLabel18.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel5.setText("Opciones");
        jLabel5.setToolTipText("");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1065, 78, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseEntered
        // TODO add your handling code here:
        imagen_gif_guardar();
    }//GEN-LAST:event_botonGuardarMouseEntered

    private void botonGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseExited
        // TODO add your handling code here:
        imagen_png_guardar();
    }//GEN-LAST:event_botonGuardarMouseExited

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:
        idCita=Integer.parseInt(txtid.getText().trim());
        fecha=((JTextField)txtFecha.getDateEditor().getUiComponent()).getText();
        hora=txtHora.getText();
        motivo=txtMotivo.getText();
        idPaciente=txtidPaciente.getText();
        idEspecialista=txtidEspecialista.getText();
        metodos.agregar_cita(idCita,fecha, hora, motivo,
                             idPaciente,idEspecialista,precio);
        txtid.setText("Ingrese el ID");
        txtid.setForeground(new Color(153,153,153));
        txtvalidar.setText("");
        limpiar();
        bloquear();
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPrecioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPrecioMousePressed
        // TODO add your handling code here:
        if (txtPrecio.getText().equals("Ingrese el Precio")) {
            txtPrecio.setText("");
            txtPrecio.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtPrecioMousePressed

    private void txtidEspecialistaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtidEspecialistaMousePressed
        // TODO add your handling code here:
        if (txtidEspecialista.getText().equals("Ingrese el idEspecialista")) {
            txtidEspecialista.setText("");
            txtidEspecialista.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtidEspecialistaMousePressed

    private void txtidPacienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidPacienteKeyReleased
        // TODO add your handling code here:
        if(txtidPaciente.getText() != ""){
            String campo=txtidPaciente.getText();
            boolean isNumeric =  campo.matches("[+-]?\\d*(\\\\d+)?");

            if(isNumeric == false){
                validaridP.setText("Solo numeros enteros");
            }
        }

        if(txtidPaciente.getText().equals("")){
            validaridP.setText("");
        }
    }//GEN-LAST:event_txtidPacienteKeyReleased

    private void txtidPacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtidPacienteMousePressed
        // TODO add your handling code here:
        if (txtidPaciente.getText().equals("Ingrese el idPaciente")) {
            txtidPaciente.setText("");
            txtidPaciente.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtidPacienteMousePressed

    private void txtMotivoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMotivoMousePressed
        // TODO add your handling code here:
        if (txtMotivo.getText().equals("Ingrese el Motivo")) {
            txtMotivo.setText("");
            txtMotivo.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtMotivoMousePressed

    private void txtidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyReleased
        // TODO add your handling code here:
        validacion();
    }//GEN-LAST:event_txtidKeyReleased

    private void txtidMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtidMousePressed
        // TODO add your handling code here:
        if (txtid.getText().equals("Ingrese el ID")) {
            txtid.setText("");
            txtid.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtidMousePressed

    private void txtHoraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHoraMousePressed
        // TODO add your handling code here:
        if (txtHora.getText().equals("Ingrese la Hora")) {
            txtHora.setText("");
            txtHora.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtHoraMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private lu.tudor.santec.jtimechooser.demo.JTimeChooserDemo jTimeChooserDemo1;
    private com.toedter.calendar.JDateChooser txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtMotivo;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtidEspecialista;
    private javax.swing.JTextField txtidPaciente;
    private javax.swing.JLabel txtvalidar;
    private javax.swing.JLabel validarCa;
    private javax.swing.JLabel validarapeMa;
    private javax.swing.JLabel validarapePa;
    private javax.swing.JLabel validaridE;
    private javax.swing.JLabel validaridP;
    private javax.swing.JLabel valiidarnombre;
    // End of variables declaration//GEN-END:variables
}
