/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import Alertas.Backup;

/**
 *
 * @author Gibran Ramses
 */
public final class Configuracion extends javax.swing.JPanel {

    /**
     * Creates new form ConsultaEspecialista
     */
    public Configuracion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnCrear = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnRest = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(169, 195, 212));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1284, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnCrear.setBackground(new java.awt.Color(67, 141, 184));
        BtnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCrearMouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CONFIGURACION/GUARDAR.png"))); // NOI18N

        javax.swing.GroupLayout BtnCrearLayout = new javax.swing.GroupLayout(BtnCrear);
        BtnCrear.setLayout(BtnCrearLayout);
        BtnCrearLayout.setHorizontalGroup(
            BtnCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnCrearLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BtnCrearLayout.setVerticalGroup(
            BtnCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnCrearLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(BtnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 220, 220));

        BtnRest.setBackground(new java.awt.Color(67, 141, 184));
        BtnRest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnRestMouseClicked(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CONFIGURACION/RESTAURAR.png"))); // NOI18N

        javax.swing.GroupLayout BtnRestLayout = new javax.swing.GroupLayout(BtnRest);
        BtnRest.setLayout(BtnRestLayout);
        BtnRestLayout.setHorizontalGroup(
            BtnRestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnRestLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BtnRestLayout.setVerticalGroup(
            BtnRestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnRestLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(BtnRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 220, 220));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("<html> Restaurar<br> la <br>  base de datos </html>");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 490, 220, 80));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("<html>\nCrear respaldo <br>\nde la <br> \nbase de datos\n</html>");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 220, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCrearMouseClicked
        // TODO add your handling code here:
            Backup a = new Backup(null,true);
            a.setVisible(true);
    }//GEN-LAST:event_BtnCrearMouseClicked

    private void BtnRestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRestMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BtnRestMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnCrear;
    private javax.swing.JPanel BtnRest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
